version: '3.6'
services:
  phoenix:
    build: 
      context: .
    depends_on:
    environment:
      MIX_ENV: prod
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app