version: '3.8'

services:
  phoenix:
    build: .
    #depends_on:
    environment:
      MIX_ENV: prod
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app

#volumes: